Scc 2962
NYPL/nypl-core pull request #81
Opened 2022-01-11 22:09 UTC by charmingduchess

Removed a recap location and added a location code

2022-01-12 01:40 UTC, nonword requested changes
Looking good. A couple things:
 - See note on the new location label
 - We should also update the version declaration in the README
 
I verified your changes using `./vocabularies/scripts/validate-changes` (i.e. `python validate-changes.py recapCustomerCodes` and `python validate-changes.py locations`), which prints out a report on what has changed in the named json-ld file between the current branch and `master`. It shows the csv to json-ld process you ran produced the right changes. (This is a script we've written to address diffing json files. We may want to include it as a step in the README.)

2022-01-12 01:40 UTC, nonword commented on vocabularies/csv/locations.csv
> +map08, Schwarzman Building - Map Division Room 177, SASB - Map Division - Rm 117, Research,,,ma,1106,false,map,,true,
I'm checking with people, but I think this label may need to include "M1A" qualifier - i.e. "Schwarzman Building - M1A - Map Division Room 117" and "SASB - M1A - Map Division Room 117".

Also, make sure there's no whitespace before the label as it does get rendered into the json-ld. (Which is probably harmless, but could change how a list of locations is sorted, for example.)

2022-01-12 15:54 UTC, charmingduchess commented
Put the changes you requested, only I followed the formatting of the adjacent locations for adding M1A (the other ones didn't have M2 or M1 separated by hyphens).

2022-01-12 17:58 UTC, nonword commented on vocabularies/csv/locations.csv
> +map08,Schwarzman Building M1A - Map Division Room 177, SASB M1A - Map Division - Rm 117, Research,,,ma,1106,false,map,,true,
Still a leading space in front of the altLabel

2022-01-12 19:55 UTC, nonword approved these changes
Looks good!

2022-01-14 15:40 UTC, nonword approved these changes

2022-01-25 15:58 UTC, merged